// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvtRCqzjwxjZ3IILudndOz-3qiAdmyIrY',
    appId: '1:167947904654:web:e50cfd7bfe37bb24268bdf',
    messagingSenderId: '167947904654',
    projectId: 'uconverse-c940b',
    authDomain: 'uconverse-c940b.firebaseapp.com',
    storageBucket: 'uconverse-c940b.appspot.com',
    measurementId: 'G-TTJGJQ9860',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvXZV0RAr5Vz00i3zRv8xlY5XpG5np9-A',
    appId: '1:167947904654:android:5d87d28e385e4e25268bdf',
    messagingSenderId: '167947904654',
    projectId: 'uconverse-c940b',
    storageBucket: 'uconverse-c940b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgln8DcU0QtciwnXsCW6q_eBXg4KQ2m_U',
    appId: '1:167947904654:ios:6f82382443b79f25268bdf',
    messagingSenderId: '167947904654',
    projectId: 'uconverse-c940b',
    storageBucket: 'uconverse-c940b.appspot.com',
    iosClientId: '167947904654-jtaaqsq65rutqpgkeag17mh7ac1gllgm.apps.googleusercontent.com',
    iosBundleId: 'com.example.uconverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgln8DcU0QtciwnXsCW6q_eBXg4KQ2m_U',
    appId: '1:167947904654:ios:6f82382443b79f25268bdf',
    messagingSenderId: '167947904654',
    projectId: 'uconverse-c940b',
    storageBucket: 'uconverse-c940b.appspot.com',
    iosClientId: '167947904654-jtaaqsq65rutqpgkeag17mh7ac1gllgm.apps.googleusercontent.com',
    iosBundleId: 'com.example.uconverse',
  );
}
